services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 6003:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/portainer/data:/data

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 6001:80 # HTTP
      - 6002:443 # HTTPS
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile:ro
      - ./services/caddy/data:/data
      - ./services/caddy/config:/config

  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./services/homer/assets:/www/assets
      - ./homer-config.yaml:/www/assets/config.yml:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 6004:443
    volumes:
      - ./services/pihole/etc-pihole:/etc/pihole
      - ./services/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 6005:3001
    volumes:
      - ./services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 6006:80
    volumes:
      - ./services/vaultwarden/data:/data
