networks:
  proxy-network:

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile:ro
      - ./services/caddy/data:/data
      - ./services/caddy/config:/config
    networks:
      - proxy-network

  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./services/homer/assets:/www/assets
    networks:
      - proxy-network

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
      FTLCONF_webserver_api_password: "123"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 6001:443
    volumes:
      - ./services/pihole/etc-pihole:/etc/pihole
      - ./services/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      - proxy-network

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 6002:3001
    volumes:
      - ./services/uptime-kuma/data:/app/data

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 6003:80
    volumes:
      - ./services/vaultwarden/data:/data
